version: "3"
volumes:
  psql:
services:
  psql:
    image: postgres:latest  
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - psql:/var/lib/postgresql/data
    ports:
      - 5555:5432 
      