# Generated by Django 5.1.1 on 2024-10-07 18:34

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=pathlib.PureWindowsPath('D:/programming/web/django_projects/django-crm/crm/uploads'), verbose_name='Фото профиля'),
        ),
    ]
