# Generated by Django 5.1.1 on 2024-10-10 16:26

import django.core.validators
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0002_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_shop_employee',
            field=models.BooleanField(default=False, verbose_name='Сотрудник магазина'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fiz_tin',
            field=models.CharField(default='', max_length=12, validators=[django.core.validators.RegexValidator('(\\d{12})')], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=pathlib.PureWindowsPath('D:/programming/web/django_projects/django-crm/crm/uploads'), validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Фото профиля'),
        ),
    ]
